In [8]:
matrix = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])


In [7]:
import numpy as np
a = np.array([32,68,100,212,77])
a = (a - 32) * ( 5 / 9 )
print(a)

[  0.          20.          37.77777778 100.          25.        ]


In [3]:
from PIL import Image

In [14]:
with Image.open('image.jpg') as img:
    arr = np.array(img)
    print(arr)
    print(img.mode)


[[[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 [[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 [[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 ...

 [[ 6  3 18]
  [ 6  3 18]
  [ 6  3 18]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 [[ 9  4 19]
  [ 9  4 19]
  [ 9  4 19]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 [[ 9  4 19]
  [ 9  4 19]
  [ 9  4 19]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]]
RGB


In [13]:
arr.shape


(322, 537, 3)