In [2]:
import numpy as np

In [ ]:
arr = np.arange(10,49)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
arr = np.arange(9)
matrix = arr.reshape(3,3)
print(matrix)

In [5]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[3.72252956e-01 1.29776003e-01 9.43809167e-01]
  [8.72387537e-02 2.03528048e-01 4.02059616e-01]
  [3.95801317e-01 9.22634396e-01 9.03488507e-04]]

 [[8.55706170e-01 7.30678486e-01 2.33677678e-01]
  [7.20989987e-01 1.82296159e-01 4.76486580e-01]
  [6.47505036e-01 5.47370289e-01 5.09700444e-01]]

 [[2.88275310e-01 9.93091911e-01 5.79843765e-01]
  [4.38178232e-01 4.70993979e-01 6.20005693e-01]
  [8.81587881e-01 3.75078122e-01 9.00966540e-01]]]


In [3]:
random_array = np.random.rand(10, 10)
maxi = 0
mini = list(random_array[0])[0]
for a in random_array:
    if maxi < max(list(a)):
        maxi = max(list(a))
    if mini > min(list(a)):
        mini = min(list(a))
print(maxi, mini)   

0.9933082869663382 0.008173255691371506


In [ ]:
random_vector = np.random.rand(30)

# Calculate the mean value
mean_value = np.mean(random_vector)

print("Random Vector:", random_vector)
print("Mean Value:", mean_value)

Random Vector: [0.46926099 0.18208188 0.98914124 0.48675458 0.94585464 0.89554147
 0.92117659 0.53223072 0.29202985 0.89102015 0.3197182  0.29896355
 0.26760364 0.8938418  0.90382106 0.2772697  0.96521307 0.11440624
 0.38248145 0.33048011 0.57146798 0.36028965 0.28589035 0.32674568
 0.11128187 0.186058   0.41555585 0.80506986 0.55178731 0.59577574]
Mean Value: 0.51896043975261


In [ ]:
import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Normalize the matrix
min_value = random_matrix.min()
max_value = random_matrix.max()
normalized_matrix = (random_matrix - min_value) / (max_value - min_value)

print("Original Random Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)