In [2]:
import numpy as np

In [ ]:
arr = np.arange(10,49)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
arr = np.arange(9)
matrix = arr.reshape(3,3)
print(matrix)

In [5]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[3.72252956e-01 1.29776003e-01 9.43809167e-01]
  [8.72387537e-02 2.03528048e-01 4.02059616e-01]
  [3.95801317e-01 9.22634396e-01 9.03488507e-04]]

 [[8.55706170e-01 7.30678486e-01 2.33677678e-01]
  [7.20989987e-01 1.82296159e-01 4.76486580e-01]
  [6.47505036e-01 5.47370289e-01 5.09700444e-01]]

 [[2.88275310e-01 9.93091911e-01 5.79843765e-01]
  [4.38178232e-01 4.70993979e-01 6.20005693e-01]
  [8.81587881e-01 3.75078122e-01 9.00966540e-01]]]


In [3]:
random_array = np.random.rand(10, 10)
maxi = 0
mini = list(random_array[0])[0]
for a in random_array:
    if maxi < max(list(a)):
        maxi = max(list(a))
    if mini > min(list(a)):
        mini = min(list(a))
print(maxi, mini)   

0.9933082869663382 0.008173255691371506


In [5]:
random_vector = np.random.rand(30)

# Calculate the mean value
mean_value = np.mean(random_vector)

print("Random Vector:", random_vector)
print("Mean Value:", mean_value)

Random Vector: [0.46926099 0.18208188 0.98914124 0.48675458 0.94585464 0.89554147
 0.92117659 0.53223072 0.29202985 0.89102015 0.3197182  0.29896355
 0.26760364 0.8938418  0.90382106 0.2772697  0.96521307 0.11440624
 0.38248145 0.33048011 0.57146798 0.36028965 0.28589035 0.32674568
 0.11128187 0.186058   0.41555585 0.80506986 0.55178731 0.59577574]
Mean Value: 0.51896043975261


In [15]:

random_matrix = np.random.rand(5, 5)

min_value = random_matrix.min()
max_value = random_matrix.max()
normalized_matrix = (random_matrix - min_value) / (max_value - min_value)

print("Original Random Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Original Random Matrix:
[[0.09972728 0.29321846 0.18822456 0.74644207 0.23705673]
 [0.29246569 0.64488137 0.73574272 0.56303584 0.14604469]
 [0.5239487  0.22354665 0.98343912 0.37450247 0.14279902]
 [0.34251195 0.77649814 0.81935003 0.13384749 0.97961435]
 [0.29785297 0.64516145 0.87359243 0.56393984 0.0445572 ]]

Normalized Matrix:
[[0.05876147 0.26484828 0.15301963 0.74757523 0.20503061]
 [0.26404651 0.63940327 0.73617939 0.55222987 0.10809399]
 [0.51059829 0.19064107 1.         0.35142361 0.10463704]
 [0.31735061 0.77958785 0.82522926 0.09510279 0.99592625]
 [0.26978448 0.63970158 0.88300265 0.55319271 0.        ]]


In [20]:
matrix1 = np.array([
    [1, 2, 2],
    [3, 4, 2],
    [5, 6, 2],
    [7, 8, 2],
    [9, 10, 2]
])
matrix1.shape

matrix2 = np.array([
    [1, 2],
    [2, 3],
    [3, 4]
])

matrix = np.dot(matrix1, matrix2)
matrix

array([[11, 16],
       [17, 26],
       [23, 36],
       [29, 46],
       [35, 56]])

In [22]:
matrix1 = np.array([
    [1, 2, 2],
    [3, 4, 2],
    [5, 6, 2]

])

matrix2 = np.array([
    [7, 8, 2],
    [9, 10, 2],
    [5, 6, 2]
])

result_matrix = np.dot(matrix1, matrix2)
result_matrix

array([[ 35,  40,  10],
       [ 67,  76,  18],
       [ 99, 112,  26]])

In [25]:
matrix1 = np.array([
    [1, 2, 2, 3],
    [3, 4, 2, 4],
    [5, 6, 2, 5],
    [7, 8, 2, 5],
])
matrix1 = np.transpose(matrix1)
matrix1

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [2, 2, 2, 2],
       [3, 4, 5, 5]])

In [29]:
matrix1 = np.array([
    [7, 8, 99],
    [9, 10, 2],
    [5, 6, 2]
])

determinant = np.linalg.det(matrix1)
determinant

388.00000000000006

In [ ]:
matrix_a = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])


matrix_b = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9],
                     [10, 11, 12]])


result_matrix = np.dot(matrix_a, matrix_b)

print("Matrix A (3x4):")
print(matrix_a)
print("\nMatrix B (4x3):")
print(matrix_b)
print("\nResultant Matrix (3x3):")
print(result_matrix)

In [30]:
random_matrix = np.random.rand(3, 3)

column_vector = np.random.rand(3, 1)

# Perform matrix-vector multiplication
result_vector = np.dot(random_matrix, column_vector)

print("Random Matrix (3x3):")
print(random_matrix)
print("\nColumn Vector (3x1):")
print(column_vector)
print("\nResultant Vector (3x1):")
print(result_vector)

Random Matrix (3x3):
[[0.34072371 0.72137102 0.90065997]
 [0.86416636 0.01763853 0.32655407]
 [0.48546107 0.38414735 0.3365165 ]]

Column Vector (3x1):
[[0.19083155]
 [0.18357699]
 [0.4502386 ]]

Resultant Vector (3x1):
[[0.60295984]
 [0.31517548]
 [0.31467463]]


In [31]:
A = np.array([[3, 2, -1],
              [2, -2, 4],
              [-1, 0.5, -1]])

b = np.array([[1],
              [-2],
              [0]])

# Solve the linear system Ax = b
x = np.linalg.solve(A, b)

print("Matrix A (3x3):")
print(A)
print("\nColumn Vector b (3x1):")
print(b)
print("\nSolution Vector x (3x1):")
print(x)

Matrix A (3x3):
[[ 3.   2.  -1. ]
 [ 2.  -2.   4. ]
 [-1.   0.5 -1. ]]

Column Vector b (3x1):
[[ 1]
 [-2]
 [ 0]]

Solution Vector x (3x1):
[[ 1.]
 [-2.]
 [-2.]]


In [32]:
matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

row_sums = np.sum(matrix, axis=1)
column_sum = np.sum(matrix, axis = 0)

print("Matrix:")
print(matrix)
print("\nRow Sums:")
print(row_sums)
print("\nColumn Sums:")
print(column_sum)

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Row Sums:
[ 15  40  65  90 115]

Column Sums:
[55 60 65 70 75]
